### ISSUE TITLE
Extend staticsite

### ISSUE THREAD

**Issue by paternal** [spanezz/staticsite#11]
Hello,
is there a way to extend `staticsite` with custom commands (corresponding to [directives](https://ikiwiki.info/ikiwiki/directive/))? I know that I could write a [markdown extension](https://python-markdown.github.io/extensions/api/), but I am not sure that the code of this extension would be passed the staticsite "context" (e.g. setting and page variables).
-- Louis

**Comment by spanezz** [comment]
Unfortunately it is not possible to pass extra context to the markdown engine. I find this very frustrating, and I had to work around it with a hack to resolve links (see `staticsite.features.markdown.LinkResolver.set_page` and its use).

Now that it is possible to add [custom features](https://github.com/spanezz/staticsite/blob/master/doc/feature.md) to a site, it's possible to run arbitrary python code and interact with existing features like the markdown one (the `staticsite.features.markdown.MarkdownPages` instance is accessible from a `Feature` as `self.site.features["md"]`).

If you are still in need of this, we can see how to register hooks to `MarkdownPages` to be called when starting to render a page, which you could then use to make the `Page` object available to your markdown extension. Would that help?

**Comment by paternal** [comment]
I asked this question when I was looking for a new static site generator ([moving from Ikiwiki](https://ikiwiki.info/forum/Some_thoughts_about_Ikiwiki/)). I eventually chose [Lektor](https://www.getlektor.com/), and although I do miss Ikiwiki, I am not planning to switch to yet another static site generator.
Thanks for your reply, nonetheless.

**Comment by spanezz** [comment]
Thanks, I'll close this issue then.

Thanks for point to lektor, I didn't know if yet, and now I'm curious to check it out.
