### ISSUE TITLE
Support multiple markdown blocks with footnotes

### ISSUE THREAD

**Issue by DonKult** [spanezz/staticsite#13]
Similar to debian-policy, staticsite currently has a problem if a page has footnotes in multiple blocks – e.g. if the page is an index page of a blog: the [^1] footnotes in each block would get the same id.

By setting the right option in the right way the ids include a block-number to be unique:
```python
MARKDOWN_EXTENSION_CONFIGS = {
    'markdown.extensions.extra': {
        'markdown.extensions.footnotes': {
            'UNIQUE_IDS': True,
        },
    },
}
 ```

Setting options for extensions bundled in the extra extension is a bit tricky, an explanation can be found in [upstreams bugtracker](https://github.com/Python-Markdown/markdown/issues/553#issuecomment-285533167).

I guess that should be a builtin default, but it breaks existing links with footnotes, so perhaps it should just be a project specific setting (hint hint)… decisions decisions…

**Comment by spanezz** [comment]
This should really be the default!
