### ISSUE TITLE
Please document Features feature

### ISSUE THREAD

**Issue by DonKult** [spanezz/staticsite#17]
One of the best features of staticsite is that it has documentation! Sadly the new Features feature isn't really documented apart from being mentioned in NEWS and of course in code.

Would be nice if an example hello-world Feature could be added so a non-native python-speaker has an easier time understanding how to set it up. Figuring out that a `FEATURES` dict is required and the content thereof wasn't super hard but could really be easier…

(Also, shouldn't staticsite skip modules without a `FEATURES` attribute given it just crashes later instead of just printing a warning?)

**Comment by spanezz** [comment]
I could reproduce the crash. On it...
