### ISSUE TITLE
GitHub/repository mode?

### ISSUE THREAD

**Issue by TobiX** [spanezz/staticsite#4]
I wonder if you would be interested in a "GitHub mode".

Usecase: When publishing a software project on GitHub, the README.md is the main entry point into the documentation, maybe linking other markdown documents in the repository. It should be easy to turn this structure into a nice homepage for the project (and push it to the gh-pages branch).

Modification needed:
- [x] Treat README.md as index.
- [x] Ignore .git directory
- [x] Maybe(?) load config file from alternate location (having it at the repo root is kinda ugly)

If you think something like this sounds useful, I'll start working on it...

**Comment by spanezz** [comment]
By all means, go ahead! I think it would be really useful, for publishing to static pages, for building documentation for offline reading, or for live preview (`ssite serve`) while editing documentation.

**Comment by TobiX** [comment]
Seems GItHub beat me to it: https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3 - I'll probably still finish my changes when I get around to it...

**Comment by spanezz** [comment]
I've merged the pull request and I'm closing the issue. I guess somewhere it should be advertised that staticsite can now be used as live preview for gitub repo documentation, though I'm not good at advertising :/
Can you give me a link to a github repo that has pages in it, that I could use as an example?
