### ISSUE TITLE
insufficient runtime dependencies in setup.py/Debian

### ISSUE THREAD

**Issue by DonKult** [spanezz/staticsite#5]
Hi,

installing staticsite in Debian left me with an unresolved runtime dependency on python3-slugify I had not installed and a few more I had just by chance. Looking at the buildlog shows lines like these: `I: dh_python3 pydist:191: Cannot find package that provides yaml. Please add package that provides it to Build-Depends or add "yaml python3-yaml" line to debian/py3dist-overrides or add proper dependency to Depends by hand and ignore this info.`

It seems like everything is picked up correctly if you would use `requires=[ 'unidecode', 'markdown', 'toml', 'PyYAML', 'jinja2', 'python_dateutil', 'livereload', 'python_slugify' ],` in setup.py (slugify added and yaml & dateutil converted to the name given in their egg files in Debian) but I know next to nothing about the python ecosystem to judge if that would really be the correct/best change.

**Comment by spanezz** [comment]
I also know next to nothing about the python ecosystem, so I went with your suggestion, that at least was tested and fixes your case.
