### ISSUE TITLE
Settings is singleton?

### ISSUE THREAD

**Issue by TobiX** [spanezz/staticsite#8]
Currently, `settings` in `staticsite/core.py` is a singleton, which makes unittest using different configuration a bit awkward. I have a simple workaround in my branch, so this is a minor issue.

**Comment by spanezz** [comment]
For the settings singleton I followed what Django does, maybe we can follow what Django does also for settings. Would you like something like [`override_settings`](https://docs.djangoproject.com/en/1.10/topics/testing/tools/#django.test.override_settings) also in staticsite?

**Comment by TobiX** [comment]
Well, I wanted to test the behaviour with multiple different settings files, so I came up with this ugly hack: https://github.com/TobiX/staticsite/commit/d790097fed0b693715c999328418d932fec8c6dd#diff-423890b7e3c2aa4791f9e203b7f194cbR24 - If the settings were a member of, for example SiteCommand, this wouldn't be a problem, since I could construct new objects for each test.

**Comment by spanezz** [comment]
I'll have a look if I can make settings part of Site

**Comment by spanezz** [comment]
Should be done in 9d34a95cf5432c2b30e1a5a973704df2302f9be0
